### ISSUE TITLE
Leverage ASP.NET Core's SPA integrations

### ISSUE THREAD

**Issue by pardahlman** [wrido/wrido#16]
ASP.NET Core has made first class citizen of single page apps. There is a [blog post](https://blogs.msdn.microsoft.com/webdev/2017/02/14/building-single-page-applications-on-asp-net-core-with-javascriptservices/) where Steve Sanderson (mr. Knockout 😉) describes some of these new features.

I _believe_ that it is easiest to achieve this by moving `Wrido.Web` into the `Wrido` application (perhaps a subfolder named `ClientApp`?). This would also make the client app appears in the solution explorer when opening `wrido.snl` in VS/Rider/IDE, which I think is a must (can perhaps be achieved in other ways).

The primary goal here is: _Make it possible for a developer to checkout wrido, then run `dotnet run` and the backend and front end builds and the application starts_.

As a secondary goal - **if applicable/makes sense** - is to leverage features developed to improve performance and ease of development. Perhaps server side rendering? Perhaps hot module reload with the real backend? Other? This will most probably be a discussion point where @Korla will have a lot of interesting input.

**Comment by Korla** [comment]
A couple points on using react with .Net JavascriptServices:

1. There’s an ”old” way and a new way. The old one uses react (and optionally) redux. This way has support for Typescript, and Hot Module Replacement. 
2. The second, newer, uses create-react-app(https://docs.microsoft.com/en-us/aspnet/core/spa/react?tabs=visual-studio). This method should have the feature that Facebook configures a version of a build system for us and we don’t need to maintain multiple Webpack npm packages and manually handle version conflicts between them and setting them up. It’s a more standardized way where we get more help from a broader community. 

Hot Module replacement should be doable if we go the second route with a bit of tweaking, so I think that’s what I’ll try first. 

A final thing to note is that when you start the frontenddevelopment server along with the backend using this method there will be a delay every time code is replaced in the running backend since the frontend server needs to restart. If this is troublesome the frontend server can be run in tje normal manner using yarn start from the frontend directory.

**Comment by pardahlman** [comment]
Option two looks very interesting 👍. Not 100% sure I understand the scenarios we want to support... if hot module works well when serving the app through `dotnet run` - why would we want to use a js dev-server?

Whatever the answer is, I think you make a valid point that was not part of the original description of this issue: frontend development should not be hindered by backend setup. If there are things that can be implemented in the backend to make it easier to develop the front end, we should create issues these things, too.

**Comment by pardahlman** [comment]
PR #43 closes this
